version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - '${DB_PORT}:3306'
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
